### ISSUE TITLE
close button in tab ?

### ISSUE THREAD

**Issue by gbaumgart** [WebCabin/wcDocker#104]
Hi,
whilst i like it as it is, my clients prefer the close button the classic way (in the tab-button). Do you have a rough pointer for me how to do it? 
thanks

**Comment by gbaumgart** [comment]
fixed in my code

**Comment by Lochemage** [comment]
@gbaumgart 

I'm glad to hear that you have implemented this feature, any chance this can be made into a pull request and brought into the main project?  I'm thinking this can be an option supplied when initializing wcDocker. What do you think?

**Comment by gbaumgart** [comment]
yes sure. Let me clean up a little. Unfortunately, I can't make PRs anymore so I'll have to send you just a link to a fork with some pointers where to find the code. Gonna do that over the weekend. 
cheers,g

**Comment by Lochemage** [comment]
@gbaumgart

I appreciate it, thanks!

**Comment by gbaumgart** [comment]
hi,
here you go:
panel.title and destroy needs to be changed:

https://gitlab.com/xamiro/wcDocker/blob/master/Code/panel.js


then in docker.js under __onMouseDownFrameTitle somewhere as first:

if ($(event.target).hasClass('wcPanelCloseIcon')) {
  return self.__closePanel(event.target.__panel);
}

then some css:

```
.wcPanelCloseIcon {
  text-align: right;
  margin-left: 4px;
  cursor: pointer;
  opacity: 0.5;
}
```

looks we need some convenience functions to retrieve objects from events. I tried the $.data api but it doesn't seem reliable, no idea why.
g

**Comment by TimNZ** [comment]
@gbaumgart Looks like this project no longer exists on gitlab, can I find the code somewhere else?

**Comment by TimNZ** [comment]
@gbaumgart Found your github version.
