### ISSUE TITLE
make markup optional

### ISSUE THREAD

**Issue by gbaumgart** [WebCabin/wcDocker#107]
Hey Jeff,

we had this already but I wanted to propose a more concrete solution: 

In order to make markup user-configurable (ie: being able to apply non-wcDocker themes), the most of the html should go into member variable.

I'd like to make a PR which: 

1. updates all init functions in order to pull and parse the markup from a member variable (overridden by subclassing) 
2. introduces a mini templating function or mixin with no further dependencies. 

There are 2 options: 

1. a function called [templatify](https://github.com/gbaumgart/xide/blob/master/utils/HTMLUtils.js#L285) which takes the markup and returns the jQuerified dom - instances as object literal

2. or we extend wcDocker/Base for markup parsing jobs, see [here](https://github.com/gbaumgart/xide/blob/master/_base/_Widget.js#L44) 

both proven well in production (originally written by IBM/dojo) and its all dcl based ready. 

Example: 

```
var panel = new wcPanel({
templateString:'<div attachTo="containerNode" class="widget" style="height: inherit"/>'
})

```
panel.init() or panel.attach() would take template string and attach "containerNode" directly as member variable panel.containerNode, as HTMLElement or/and $ automatically.

Overhead: around 100 lines

That's basically the corner problem I can't make PR's anymore because CSS/HTML is usually managed by the consuming app and not a the library. 

That also allows you to use the asked [themes](https://github.com/gbaumgart/admin-theme.git) out of the box (I'd to clean them only), and also a whole bunch of new extra features/fixes as PRs would be available to you. 
g
close this otherwise, np

**Comment by Lochemage** [comment]
@gbaumgart 

I would only be careful as a lot of the functionality of wcDocker relies on specific element/class types organized very specifically. It would be very easy for someone to completely break wcDocker by simply not knowing exactly what they are doing.

That being said, it does have a lot of potential for customization. Is it possible to implement this in a way that keeps it from becoming a "foot gun"?

**Comment by gbaumgart** [comment]
never mind
