### ISSUE TITLE
Embedded wcDocker instance or otherwise constraining panels to one layout

### ISSUE THREAD

**Issue by TimNZ** [WebCabin/wcDocker#114]
Hi @Lochemage 

I want to create panels that are effectively embedded Docker instances.

This is to allow child panels to be moved around only within that container/parent panel.

What's your recommended approach for this?

At this stage I'm looking at creating a modified version of wcIFrame that wraps around a div instead.  
I need to propagate hide/show events from the parent wcDocker down to the child wcDocker at a minimum.

**Comment by Lochemage** [comment]
@TimNZ 

I'm having trouble understanding exactly how you want to use it and why the built in wcIFrame would not work for you as it is. wcIFrame is made to simply be an iFrame inside of your panel layout. With an iFrame, you should be able to create an entirely new docker instance that is contained in this frame.

If I am misunderstanding, please elaborate your use case.

**Comment by TimNZ** [comment]
It might do.  I don't have a lot of experience with &lt;iframe&gt; beyond external src and may have dismissed it incorrectly.  Will have a play.

**Comment by TimNZ** [comment]
Played around a bit and embedded iframe is not workable.

I'm running within Electron so that's a show stopper.
Running in an iframe also creates a world of pain between
