### ISSUE TITLE
iFrame panels not working in Firefox

### ISSUE THREAD

**Issue by dpage** [WebCabin/wcDocker#28]
I have a number of iFrame panels in my app, which work fine in Chrome and Safari but remain blank in Firefox. They are being built like so:

```javascript
// Build an iFrame dock panel
function buildIFramePanel(docker, name, title, width, height, showTitle, isCloseable, isPrivate, url) {
    docker.registerPanelType(name, {
        title: title,
        isPrivate: isPrivate,
        onCreate: function(myPanel) {
            myPanel.initSize(width, height);
            
            if (showTitle == false) 
                myPanel.title(false);

            myPanel.closeable(isCloseable);

            var $frameArea = $('<div style="width:100%;height:100%;position:relative;">');
            myPanel.layout().addItem($frameArea);
            
            var iFrame = new wcIFrame($frameArea, myPanel);
            iFrame.openURL(url);
        }
    });
}
```

The result looks as follows:
![screen shot 2015-03-03 at 14 19 33](https://cloud.githubusercontent.com/assets/316438/6464277/1b88768c-c1b1-11e4-8c35-7e9f5fd4600d.png)
![screen shot 2015-03-03 at 14 19 37](https://cloud.githubusercontent.com/assets/316438/6464285/24956190-c1b1-11e4-8e6c-093016a8ff8d.png)

**Comment by Lochemage** [comment]
Dave,

I will have to get back to you on this, once I have some free time to look
deeper.

Thanks,


- Lochemage

**Comment by Lochemage** [comment]
Dave,

I'm having trouble reproducing this issue.  It seems like it may have to do
with the content you are trying to put into your frame.  Do you have any
more information I can use?

Thanks,

- Lochemage

**Comment by dpage** [comment]
Hi,

The content being used in the screenshots is the Sphinx generated documentation that is served from my app. If you're brave you can find the complete code in the web/ directory at http://git.postgresql.org/gitweb/?p=pgadmin4.git;a=summary, but beware it is a very early incarnation of what will be a large and complex app. The JS that creates the panels is here: http://git.postgresql.org/gitweb/?p=pgadmin4.git;a=blob;f=web/pgadmin/browser/templates/browser/js/browser.js;h=258d450f6d405d59ad44ccb014086c47093f1811;hb=caff78053b48a15579e987fa58decca3e82e1976

However... I see exactly the same problem with other panels I have which load either http://www.pgadmin.org/ or http://www.postgresql.org/, so I'm fairly sure it's not a content issue, but either something wrong with my code, a Firefox bug, or a wcDocker bug.

I'm happy to provide any further info you may need, or can run any tests etc. if you like.

Thanks.

**Comment by Lochemage** [comment]
Dave,

I've just tried both those pages on a local build of my demo page and it
seems to work on FF.


​

​

- Lochemage

**Comment by dpage** [comment]
Hi

Can you send me the test code you used, so I can try it here?

Thanks.

On Thu, Mar 5, 2015 at 5:25 PM, Jeff Houde <notifications@github.com> wrote:

> Dave,
>
> I've just tried both those pages on a local build of my demo page and it
> seems to work on FF.
>
>
> ​
>
> ​
>
> - Lochemage
>
> On Thu, Mar 5, 2015 at 9:13 AM, Dave Page <notifications@github.com>
> wrote:
>
> > Hi,
> >
> > The content being used in the screenshots is the Sphinx generated
> > documentation that is served from my app. If you're brave you can find
> the
> > complete code in the web/ directory at
> > http://git.postgresql.org/gitweb/?p=pgadmin4.git;a=summary, but beware
> it
> > is a very early incarnation of what will be a large and complex app. The
> JS
> > that creates the panels is here:
> >
> http://git.postgresql.org/gitweb/?p=pgadmin4.git;a=blob;f=web/pgadmin/browser/templates/browser/js/browser.js;h=258d450f6d405d59ad44ccb014086c47093f1811;hb=caff78053b48a15579e987fa58decca3e82e1976
> >
> > However... I see exactly the same problem with other panels I have which
> > load either http://www.pgadmin.org/ or http://www.postgresql.org/, so
> I'm
> > fairly sure it's not a content issue, but either something wrong with my
> > code, a Firefox bug, or a wcDocker bug.
> >
> > I'm happy to provide any further info you may need, or can run any tests
> > etc. if you like.
> >
> > Thanks.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/WebCabin/wcDocker/issues/28#issuecomment-77405866>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WebCabin/wcDocker/issues/28#issuecomment-77408206>.
>



-- 
Dave Page
Blog: http://pgsnake.blogspot.com
Twitter: @pgsnake

EnterpriseDB UK: http://www.enterprisedb.com
The Enterprise PostgreSQL Company

**Comment by Lochemage** [comment]
Dave,

All I did was take the demonstration page (index.html found in the repo)
and changed the "Widget Panel" found in demo.js to have an iframe instead
of all the other widgets.

var iFrame = new wcIFrame($scene, myPanel);
iFrame.openURL('http://www.postgresql.org/');

- Lochemage

**Comment by Lochemage** [comment]
Dave,

Upon a second inspection, I did notice that I am getting a lot of Cross Origin errors when loading the pgadmin page.  Are you sure your page isn't properly loading due to that?

**Comment by dpage** [comment]
Hi

I don't see any cross origin errors here, but I have figured it out. Whilst this works on Chrome and Safari:
```javascript
            var $frameArea = $('<div style="width:100%;height:100%;position:relative;">');
            myPanel.layout().addItem($frameArea);

            var iFrame = new wcIFrame($frameArea, myPanel);
            iFrame.openURL(url);
```
On Firefox, the following is needed:
```javascript
            var $frameArea = $('<div style="width:100%;height:100%;position:relative;">');
            myPanel.layout().addItem($frameArea).parent().css('height', '100%');

            var iFrame = new wcIFrame($frameArea, myPanel);
            iFrame.openURL(url);
```
Setting the height doesn't matter on Chrome/Safari of course, so I just do that in all cases now.

Thanks for helping figure this out!
