### ISSUE TITLE
Unable to dock a panel if it is in floating state

### ISSUE THREAD

**Issue by alinoson** [WebCabin/wcDocker#29]
Hi,
I really appreciated the library, it is so cool and powerfull. I have never seen such well done docking manager in Html5/jquery. I m exploring to use it and from the demo app i found out that if a pane went in floating state i cannot dock it anymore.
Is that a bug or is there any way to dock a panel from a floating state?

Thanks for your precious help.

Best regards.

**Comment by Lochemage** [comment]
It might be a bit weird, but what you have to do is grab the panel by its
tab widget; If you grab it on its title bar it will only move the window
around rather than try to re-dock it.

- Lochemage

**Comment by alinoson** [comment]
Hi Lochemage,

Thanks so much, it s not really a bug, i was grabing the title bar instead of the tab widget to re-dock it.

Best regards.
