### ISSUE TITLE
wcSplitter Directional Pane Selection Undefined

### ISSUE THREAD

**Issue by cganas** [WebCabin/wcDocker#31]
I was following along the tutorial [here](http://docker.api.webcabin.org/tutorial-3.0-widgets.html) and was trying to implement a wcSplitter with the following code.

```javascript
$(document).ready(function() {
    var myDocker = new wcDocker(document.body,
                                {"theme": "shadow"});

    myDocker.registerPanelType('StaticView', {
        onCreate: function(myPanel, options) {
            var layout = myPanel.layout();
            var container = $("<div id='static-container'></div>");

            layout.addItem(container);

            var splitter = new wcSplitter(container, myPanel, wcDocker.ORIENTATION.HORIZONTAL);

            splitter.initLayouts();

            var vtimelineLayout = splitter.left();
            vtimelineLayout.addItem($("<p>test left</p>"));

            var traceLayout = splitter.right();
            traceLayout.addItem($("<p>test right</p>"));
        },
    });
    var staticPanel = myDocker.addPanel("StaticView", wcDocker.DOCK_RIGHT);
});
```

However both `vtimelineLayout` and `traceLayout` were undefined. I looked into the code and noticed that left and right were defined as follows:

```javascript

  /**
   * Gets, or Sets the element associated with the left side pane (for horizontal layouts).
   *
   * @param {wcLayout|wcPanel|wcFrame|wcSplitter} [item] - If supplied, the pane will be replaced with this item.
   *
   * @returns {wcLayout|wcPanel|wcFrame|wcSplitter|Boolean} - The current object assigned to the pane, or false.
   */
  left: function(item) {
    this.pane(0, item);
  },

  /**
   * Gets, or Sets the element associated with the right side pane (for horizontal layouts).
   *
   * @param {wcLayout|wcPanel|wcFrame|wcSplitter} [item] - If supplied, the pane will be replaced with this item.
   *
   * @returns {wcLayout|wcPanel|wcFrame|wcSplitter|Boolean} - The current object assigned to the pane, or false.
   */
  right: function(item) {
    this.pane(1, item);
  },

```

and wondered if it was supposed to instead `return this.pane(n, item)` for left, right, top, and bottom. Changing this fixed the issue for me. If this is a bug I have the code ready for a pull request.

**Comment by Lochemage** [comment]
Christopher,

heh, you are correct... that is what I get for not testing new features.
This is something I added only yesterday, or the day before, and just sort
of assumed I did it right since it was such a simple function.  It used to
be that you had to use pane() and provide the number 0 or 1, but I thought
left(), right() would be more user friendly.

I will fix this right now and update the repo, sorry about this!

- Lochemage

On Wed, Mar 25, 2015 at 6:53 PM, Christopher Ganas <notifications@github.com
