### ISSUE TITLE
Error While docking : Unable to get property '_parent' of undefined

### ISSUE THREAD

**Issue by jxc876** [WebCabin/wcDocker#36]
I setup a simple page using the instruction from the Getting Started page:

HTML:

	<div id="docker"></div>
	<div id="simple"><h2>Simple Panel!</h2></div>

JS:

	$(function(){ 
		var myDocker = new wcDocker('#docker', {
			themePath: 'libs/wcDocker/Themes'
		});
		
		myDocker.registerPanelType('SimplePanel', {
			onCreate : function(myPanel, options){
				myPanel.layout().addItem("#simple");
			}
		});
			
		var panel = myDocker.addPanel('SimplePanel', wcDocker.DOCK.LEFT);
    ...

Whenever I click the collapse button, I get an error in all three browsers (Firefox, Chrome, IE).
The error is coming from the following section of code:

    function __createCollapser(location) {
      this._collapser[location] = this.__addCollapser(location, parent);
      parent = this._collapser[location]._parent;
      this._frameList.push(this._collapser[location]._drawer._frame);
    }

The error can be seen here: https://rawgit.com/jxc876/docker-demo/master/index.html 
The project is here: https://github.com/jxc876/docker-demo

**Comment by Lochemage** [comment]
Hi,

Thank you for trying wcDocker! I have narrowed down the problem and am fixing it now.

**Comment by Lochemage** [comment]
Michael,

Thank you so much for your patience, please update and try this again, it should be fixed now!

**Comment by jxc876** [comment]
Hi Jeff,

Thanks for the fast reply, looks like that fixed the docking issue ! 

----

@Lochemage 
One last question for you, I noticed that the demo page uses inline html to set the panel content, EX:

    var $themeLabel       = $('<div style="width:100%;text-align:right;margin-top:20px;white-space:nowrap;">Select theme: </div>');
    ...
    myPanel.layout().addItem($themeLabel, 0, 1)

The documentation for `addItem()` mentions that it can either accept a *jquery selector*, *jquery object*, or *dom node*. 

However, when I use a selector only the very first panel of that type gets the content. Any further panels of the same type are empty. 

When I use inline html (like the demo page), or use `panel.addItem($querySelector.html())` then every panel of that type gets the content. Wondering if this is a bug or this if this is the intended behavior. Thanks a bunch.
