### ISSUE TITLE
Adding wcIFrame as floating panel hides the iframe DOM element

### ISSUE THREAD

**Issue by arpanmukherjee1** [WebCabin/wcDocker#38]
Adding a floating panel and creating a wcIFrame on onCreate callback will not show the IFRAME DOM element. It is hidden by the panel above it.
![image](https://cloud.githubusercontent.com/assets/10557028/8247256/c5098dd2-166a-11e5-8b88-64845efdc28e.png)

**Comment by Lochemage** [comment]
Please let me know if you find any problems with this update. Thanks.

**Comment by arpanmukherjee1** [comment]
@Lochemage 

I think this issue appeared again. Please verify and re-open this. I will try to find the exact scenario when it occurs.

**Comment by Lochemage** [comment]
@arpanmukherjee1 

Perhaps further details are needed, I just tried it on both the online demo site and the latest default branch and it works as expected.

**Comment by arpanmukherjee1** [comment]
@Lochemage 

Yes you are correct, this is not occurring in normal scenario. Will confirm when I hit the use case again.
