### ISSUE TITLE
IFrame panel click does not focus the panel

### ISSUE THREAD

**Issue by arpanmukherjee1** [WebCabin/wcDocker#40]
Dynamically created IFrame panels do not get focus when layout of a non-active panel is clicked,

**Comment by Lochemage** [comment]
arpanmukherjee1,

Could you be more specific, I am not sure I understand what you mean by this bug. Thanks.

**Comment by arpanmukherjee1** [comment]
Ref screenshot
![frame](https://cloud.githubusercontent.com/assets/10557028/8454616/846b718a-201c-11e5-9694-ba21bd6a116c.jpg)

frame 1 was created after frame 2. Now clicking on the layout of frame 1 should focus the panel.

Hope the issue is clear now.

**Comment by Lochemage** [comment]
Ah, I understand.  I will look into this as soon as I am able.

**Comment by Lochemage** [comment]
Please let me know if you find any more related issues with this update.
