### ISSUE TITLE
event for tab changed? 

### ISSUE THREAD

**Issue by mc007** [WebCabin/wcDocker#44]
Hi,

for a top - tab - container, I'd like to get notified when the tab is changed. So I tried 'GAIN_FOCUS' but its emitted for any other tab within the same tab container as well. Is that normal? I guess so since I know a 'tab' isn't a necessarily just a panel;

However, the only reliable way I could figure was extending function __onMouseDownFrameTitle(event) at end for:

                   var focusFrame = self._focusFrame;
                    var cPanel  = focusFrame.currentPanel();
                    if(cPanel){
                        cPanel._emit(types.DOCKER.EVENT.SELECT);
                    }

just close this ticket if its out of scope or I am somewhat on the wrong track ;-)

**Comment by Lochemage** [comment]
mc007,

GAIN_FOCUS and LOSE_FOCUS are actually working as intended, although the API descriptions for those events are misleading.  Focus events happen on the entire tabbed frame itself, not actually an individual panel.  Sorry for the confusion, I'll update the API description immediately.

The event you probably want to use is VISIBILITY_CHANGED, while there are other ways to change visibility, a tab changing is one. Whenever you receive this event, use `wcPanel.isVisible()` to get the current state.

```
myPanel.on(wcDocker.EVENT.VISIBILITY_CHANGED, function() {
  if (myPanel.isVisible()) {
    // Do something, the panel is now visible.
  } else {
    // Do something else, the panel is no longer visible.
  }
});
```

If, for whatever reason, it becomes necessary that you ONLY receive an event during a tab change, and visibility change is not enough for you, let me know, I can add a specific tab change event if needed.

**Comment by mc007** [comment]
I tried VISIBILITY_CHANGED but was missing the isVisible part.
Ok then, we can close this ticket :-)

Thank you again, top notch support!

**Comment by Lochemage** [comment]
Actually, when writing those instructions, it became apparent to me that maybe I should pass in the current visibility state as the first parameter. It shouldn't be necessary that you request the state yourself while you are receiving that event.

**Comment by mc007** [comment]
yup, I was missing that argument there too ;-)
g

**Comment by Lochemage** [comment]
I will change this real quick, once changed your code should look like this instead:
```
myPanel.on(wcDocker.EVENT.VISIBILITY_CHANGED, function(visible) {
  if (visible) {
    // Do something, the panel is now visible.
  } else {
    // Do something else, the panel is no longer visible.
  }
});
```
