### ISSUE TITLE
some little optimization

### ISSUE THREAD

**Issue by mc007** [WebCabin/wcDocker#45]
Hi,

**Lookups**

currently its all under wcDocker. which might be probably fine for you but in large environments; JS lookups (upwards til global/window) can become a performance problem. 

I did it already for me, using a require-js like approach = AMD modules (i know, its outdated looking at ES6 and all the transpiler trallala/mess). I don't now how this can be done via plain/jQuery JS but its probably no biggy.

However, if you could manage to get your constants and enumerations into the class's scope (this) that would be great and help me to avoid to maintain a fork. Same goes for class equal checks (instanceof) which could be something like: 

var self = this,
  types = self.types,
  events = types.EVENTS,
  splitterType = types.Splitter;

if (self._is(element,splitterSplitter)){
   ...foo
}

element.emit([events.GAIN_FOCUS,events.VISIBILTY_CHANGED]);//

That doesn't looks much better but at least it reduces size and lookups. Finally I would be happy to use your library directly, possibly also to contribute in docs and little other things. wcDocker plays now really a key-role in my system. 

Btw; you can probably make quite some extra bucks on the side with your lib on 'Envato - CodeCanyon'. Just some fancy intropage and more sample files and you're done. 

well, don't bother (close it); Just saying :-)
g

**Comment by Lochemage** [comment]
mc007,

If I am understanding you correctly, you are asking me to copy all of the constants found in wcDocker to each of the other classes, like wcPanel, so that the scope lookup would find the variables faster.

While this might improve the lookup, I don't know if it would improve the overall performance by any significant amount. I would need to see performance stats on this before I committed myself to make a change like this. 

My main concern is that a change like this would require everyone using it to re-write portions of their code. I feel that an inconvenience like this would only be worth it if it proved a significant improvement that they would not have otherwise.

If optimizations are to be made, I would begin by looking at some of the bottlenecks instead. For example, resizing panels requires some massive DOM reflows which are very hard to avoid without sacrificing responsiveness.

**Comment by mc007** [comment]
hi, 
constants: yes!

sorry for the long text:

actually you can only see that when debugging chrome's V8, looking at the insane amount of machine calls(ASM) for each lookup and depending on the size of the scope and some CPU internals, it doesn't look good. I guess its JS nature not being able to 'cache' the lookup.

I started a stackoverflow discussion once on this and couldn't come up with some stats at this time neither (i don't trust micro benchmarks anyways) but a few people agreed upon prevention rather ignoring lookup optimization. A while ago I turned globals into locals and it felt better indeed, not sure it really was the lookup only.

However, 
you're right; it might be a too little problem for you or your users. I just wanted to mention that this sums up very fast, your layout engine for instance just makes less than 1% in my system; but if I would do use globals anywhere else too, well... Actually I'm always at the edge of performance problems, even on the latest premium hardware. 

All in all it's not a drama; even your DOM operations itself don't cause much overhead; nor the mouse events on 'body' do; compared to Dojo's layouting classes, its still way better! 

Another tweak I would love to have is: being able to exclude certain panels from any calculation, lets call it "resume" and "pause". I see many iterations in your code, taking every panel/container into account, regardless they are visible or not; not sure I understood all. 

However, in my world I do already lots of caching for widgets but also containers; it would be great I could do same on your objects. I know that may sound little like overkill; but really, i am scratching the roof-top of memory & performance limits, just want make sure I did all I could.

Ok, thanks for listening, don't bother as said. Be glad to close this. 

btw, there is a package for OOP called "DCL". Its pretty fast and could eliminate quite some code. I am going to add this now to wcDocker :-)
g

**Comment by Lochemage** [comment]
mc007,

The layout of the entire window depends on every panel, even the invisible ones. If any panel has a min or max size constraint, it will effect the overall layout of the window. That being said, if a panel is invisible, then all of its contents won't be reflowed, so it shouldn't have a performance cost in that case.

However, there is a feature already implemented that might be close to what you are asking for. If you initialize the docker instance with the option 'hideOnResize', any panel that has been initialized with `myPanel.resizeVisible(false);` will hide its contents whenever panels are being resized. This stops any panel from reflowing its contents while it is in the middle of resizing.

```
var myDocker = new wcDocker('.container', {hideOnResize: true});

myDocker.registerPanelType('myPanel', {
  onCreate: function(myPanel) {
    myPanel.resizeVisible(false);
  }
});
```

DCL looks like an interesting library, but none of the wcDocker classes actually take advantage of an inheritance model or use mixins, so I'm not sure it would benefit from using it.

**Comment by mc007** [comment]
ok then, thanks again!
