### ISSUE TITLE
Option to hide and show panels

### ISSUE THREAD

**Issue by arpanmukherjee1** [WebCabin/wcDocker#46]
Hello

I found wcPanel.__isVisible() triggers VISIBILITY_CHANGED event and iframe listens to it.

```javascript
        myDocker.registerPanelType('My Panel', {
            faicon: 'gears',
            onCreate: function (myPanel) {

                var $container = $('<div style="position:absolute;top:0px;left:0px;right:0px;bottom:0px;"></div>');
                myPanel.layout().addItem($container);

                var iFrame = new wcIFrame($container, myPanel);
                iFrame.openURL('some url');
              }
        });


        myDocker.addPanel('My Panel', wcDocker.DOCK.TOP);
        var first = myDocker.findPanels('My Panel')[0];
        first.__isVisible(false);
```

But the above code does not work.

Is there a way to hide and show panel (frame + iframe) without destroying it ?

**Comment by Lochemage** [comment]
arpanmukherjee1,

For future reference, any function that starts with '__' is meant to be used internally only, they may not work exactly like you would expect. This is also why they are not documented in the API.

In this case, __isVisible() is only meant to toggle the visibility flag in a way that alerts all the proper evocations about the change, it does not actually make the panel invisible itself. A panels visibility state is only effected when a tab is selected (or hidden). So the actual hiding of the panel is handled by the tab system, not the panel itself.

Unfortunately, there is no way to simply hide a panel on demand, at least, not in a way that removes the tab item or frame completely, except by destroying it.

What is your use case for hiding a panel?

**Comment by arpanmukherjee1** [comment]
Lochemage,

Thanks, I supposed that __isVisible() is internal by tried it out anyway. I missed that the tab layout hides the panels.

In my case the panels will have contents that are rendered when the panel is created for the first time. Now its required that the state (including scroll position and others) do not change but the user will remove the panel and it must be restored at a later time.

Saving the content sate is not always possible, for all panels, so the alternate is to hide it. No serialization/deserialization needed in that case.

I thought of programmatically collapsing the docked panels and hiding the title. Is this a viable workaround? Also will it work on floating panels too?

**Comment by Lochemage** [comment]
arpanmukherjee1,

I've been thinking about this one, but it isn't an easy one to solve. Also, I'm still having a hard time understanding why you can't just destroy the panel and then remake it, can't you just save the scroll position and other details and restore them when a new panel is created?

**Comment by arpanmukherjee1** [comment]
Yes, saving and restoring all known properties is the 'ideal' way, but, as I said not always possible.

You see, the panels shall host contents that are rendered by 3rd party JS. I will call a method passing on the layout DIV of the panel to this method. 

So it's better just to hide it for two reasons:
  - Make the API simpler to work with and not force the user to save a transient layout.
  - Performance wise not to re-render an expensive layout.

I get it that it is a non-trivial implementation. Still, can you suggest any workarounds?

**Comment by Lochemage** [comment]
arpanmukherjee1,

Ah, I understand.  Please give me some time to think about this, we may be able to come up with a solution.

Thanks

**Comment by Lochemage** [comment]
arpanmukherjee1,

I think I can introduce a concept of a 'persistent' panel. Or at least, a panel that never really gets destroyed, just hidden and re-shown.  To the users perspective, though, the panel can be closed and re-created within the view.

Only one problem with this feature, maybe you can help me with; What happens when the user opens two of the same window?

**Comment by arpanmukherjee1** [comment]
Ah, I see. That is exactly what I was looking for.

Ok, expanding on the scenario, if I have registered a panel type eg. 'myType' and added two panels, then what is the result of calling myDocker.hide('myType'). Right?

In my opinion hide() can be the method of wcPanel and not wcDocker. It's up-to the developer to ensure the right panel is selected before calling hide() on that panel.

Does it answer your question?

**Comment by Lochemage** [comment]
arpanmukherjee1,

You are correct, the hide function would not be part of wcDocker, but the wcPanel instead. However, I was more concerned about having multiple persistent panels. However, I was thinking that a persistent window would automatically hide instead of close whenever the user clicks the close button (so essentially it can never be actually closed, only hidden).

Since the user can add as many copies of the same panel as they want in their view, they could potentially clutter the docker with a bunch of persistent (never closing) copies of the same persistent panel type. Should there be some way to release their memory (to really close them instead of just hide)?

In addition, with several persistent copies of the same panel (each individually controlled), when you close all of them and re-add one, you can only get back one of the several versions of that panel back. If it was not the one you wanted, you will be force to continually add the same panels back until you got it. etc.

**Comment by arpanmukherjee1** [comment]
Yes, that is the way it will work.

Ok, expanding the scenario you are suggesting that I have a registered panel type eg 'myType', now if panel is added two or more times, calling 'myDocker.hide('myType')' will hide or show  which panel. Right?

Give the panels an unique ID that can be passed as parameter addPanel()

**Comment by Lochemage** [comment]
arpanmukherjee1,

There won't be any chance to call a function like `addPanel()` with an ID value as you say.  I'm talking about when the user closes the panel and opens a new one completely using the front end interface, they wouldn't have any access to code at all. As far as code is concerned, to re-show a previously hidden persistent panel you would just have the find that panel and call `show()`.

Anyway, I can't be sure when I will have a chance to implement this as I am very busy lately with other projects, but it will be on my list.

**Comment by arpanmukherjee1** [comment]
Lochemage,

I suppose you are considering a new type of panel like `wsHideablePanel. `

Instead of this we can make `wcPanel` have `hideOnClose` bool property that is checked when the 'close' button is clicked. Also already hidden panel can be programmatically destroyed. I think that will not effect the existing methods/functionality.

Yes, that's a valid point that user wont be able to give an ID.

**Comment by Lochemage** [comment]
arpanmukherjee1,

Yes, it will just be an option when registering the panel type.

```
wcDocker.registerPanelType('my panel', {
  isPersistent: true,
  onCreate: function(myPanel) {...}
});
```

**Comment by arpanmukherjee1** [comment]
OK, that sounds good.

**Comment by Lochemage** [comment]
arpanmukherjee1,

I have just implemented this feature, please let me know how this works for you:

```
myDocker.registerPanelType('persistent panel', {
  isPersistent: true,
  onCreate: function(myPanel) {
    myPanel.on(wcDocker.EVENT.PERSISTENT_CLOSED, function() {
      // The user has closed this panel, but instead of being destroyed, it is only hidden.
    });
    myPanel.on(wcDocker.EVENT.PERSISTENT_OPENED, function() {
      // The user added this panel type, but actually only re-shown this persistent version of the panel instead.
    });
  }
});
```

**Comment by arpanmukherjee1** [comment]
@Lochemage 
I tried out the enhancement and it's working as expected. :)
In process of integrating it with my code.

Thanks.

**Comment by arpanmukherjee1** [comment]
@Lochemage,
persistent panel do not work as expected in case of iframe panels.

```javascript
                myDocker.registerPanelType(self.moduleName, {
                    isPersistent: true,
                    onCreate: function (panel) {
              ...

 onRender: function (panel) {            
            // iframe            
            var $container = $('<div style="position:absolute;top:0px;left:0px;right:0px;bottom:0px;"></div>');
            panel.layout().addItem($container);
            var iFrame = new wcIFrame($container, panel);
            iFrame.openHTML('<div> lkdsjfglskdjlksdjglkdsg </div>');
      ...
```

![screen](https://cloud.githubusercontent.com/assets/10557028/8976530/dd418498-36ab-11e5-9468-337e0e1b9382.jpg)

Notice the frame is closed and the content is still visible.

Should i open another thread ?

**Comment by Lochemage** [comment]
@arpanmukherjee1 

Thanks for catching this one, I will look into it as soon as I can.

No need to make another ticket, this one should not be complete until we are satisfied that persistent panels have been implemented properly to start with.

**Comment by arpanmukherjee1** [comment]
Ok. Thanks

**Comment by Lochemage** [comment]
@arpanmukherjee1 

Please give it a try now and let me know if you find any more issues :)

**Comment by arpanmukherjee1** [comment]
@Lochemage 

I applied the fix and it works as expected. Thanks.

**Comment by arpanmukherjee1** [comment]
@Lochemage 

The issue still persists while closing the last panel.

**Comment by Lochemage** [comment]
@arpanmukherjee1 

Ok, for sure now!  It's fixed!

**Comment by Lochemage** [comment]
@arpanmukherjee1 

Closing this issue, please re-open if you find any problems.

**Comment by arpanmukherjee1** [comment]
@Lochemage 

Yes I believe it's fixed now.
