### ISSUE TITLE
Floating panel as a host for other dragged panels

### ISSUE THREAD

**Issue by bulentv** [WebCabin/wcDocker#51]
Thank you for this great library!

Enhancements : 
It would be good to make the floating panels also able to get other windows to create splitted and/or tabbed windows that are floating or popped up.

Issue:
When the user starts dragging a panel, it's like it wants to be docked somewhere as soon as possible and resists to become floated. :) I think the boundary of key positions to decide suggesting to user to dock the window to the nearest position should be tweaked to allow for a possibility to float it in more balanced way.

**Comment by Lochemage** [comment]
bulentv,

That is a good suggestion, I'll keep this on the list in case I manage to gather enough free time to do it. I suspect it would require some large scale refactoring, though.

As for your issue, I would like to keep each individual suggestion/issue separated, so I have moved it to report #52.

**Comment by Lochemage** [comment]
@bulentv 

I've created a new enhancement ticket #71 that is very similar to your floating panel suggestion. I think with some thought it can actually replace your suggestion altogether. Unfortunately, I think I will be saving that one for after the 3.0.0 release. If I keep adding more features I will never get it released!

For now, I am going to close this bug in favor of #71 instead.
