### ISSUE TITLE
Ability to configure the threshold of docking anchors.

### ISSUE THREAD

**Issue by Lochemage** [WebCabin/wcDocker#52]
This issue is taken from report #51 from bulentv:

When the user starts dragging a panel, it's like it wants to be docked somewhere as soon as possible and resists to become floated. :) I think the boundary of key positions to decide suggesting to user to dock the window to the nearest position should be tweaked to allow for a possibility to float it in more balanced way.

**Comment by Lochemage** [comment]
@bulentv,

For this, I believe the solution would be to add a custom property value when you construct an instance of wcDocker that will allow you to override the threshold of what I call docking anchors.

```
var myDocker = new wcDocker('#container', {
  anchorThreshold: '60px'
});

// or possibly something like this would be nice as well:

var myDocker = new wcDocker('#container', {
  anchorThreshold: '10%'
});
```

Will this work for you?

**Comment by Lochemage** [comment]
@bulentv,

I have implemented this feature, the wcDocker options are `edgeAnchorSize` and `panelAnchorSize`

```
var myDocker = new wcDocker('#container', {
  edgeAnchorSize: 50,
  panelAnchorSize: '15%'
}
```

Please let me know if this solves your issue.

**Comment by bulentv** [comment]
Jeff,

I tested it and it feels much better now!
Thanks for the quick response,

Bulent

**Comment by Lochemage** [comment]
I am going to close this issue as complete.

If you come across any problems related to this new feature, please re-open this issue.
