### ISSUE TITLE
IFrames become non-interactive

### ISSUE THREAD

**Issue by arpanmukherjee1** [WebCabin/wcDocker#53]
@Lochemage,

While using IFRAMES docked panels become non-interactive due to div with `wcIFrameFocus`.

![screen](https://cloud.githubusercontent.com/assets/10557028/8931369/6cb615e4-3553-11e5-948c-ccbbb9547857.jpg)

Ref screenshot: the iframe panel on the right is not getting focus due to below div.

**Comment by Lochemage** [comment]
@arpanmukherjee1 

iFrames steal mouse input such as mouse drag events from reaching wcDocker, without the drag events, if you try to move a panel and dock it somewhere over the iFrame it causes problems. The solution was to cover up the iFrame with some element that blocks the iFrame from stealing mouse focus.

However, the wcIFrameFocus element should always be set to `display: none` except in very specific situations where I need to have mouse input.  I see that yours seems to be stuck on `display: block` mode. Does clicking in that iFrame not cause the focus element to hide itself again?

Unfortunately, I've tried a number of actions but I can't seem to reproduce this, could you list more specifically what actions you took to get this?

**Comment by arpanmukherjee1** [comment]
Ah, I get why the wcIFrameFocus is required.

To reproduce the issue: In your demo site
1. close all panes except tutorial panel and control panel
2. add another tutorial panel
3. make it floating and then dock it on the right (or any other) side of the existing panel.

I tried the steps and reproduced the bug.

I tried to debug the code and `__updateFrame()` is reporting the panel as unfocused, `focus` is `false`.
ref `iframe.js` line# 260

**Comment by Lochemage** [comment]
@arpanmukherjee1 

Thank you for the detailed instructions, I am able to reproduce this bug now.

I will have some time later tonight to look into it, I'll keep you updated!

**Comment by arpanmukherjee1** [comment]
@Lochemage 
Welcome. Sounds good to me, thanks.

**Comment by Lochemage** [comment]
@arpanmukherjee1 

Try it out now, I believe I have made it better than before!

**Comment by arpanmukherjee1** [comment]
@Lochemage 
It's working as expected. Thanks
