### ISSUE TITLE
Text selection preventation during drag / resize does not work on floating panels.

### ISSUE THREAD

**Issue by bulentv** [WebCabin/wcDocker#54]
Floating panels' DOM elements are moved out of the main container which is a common approach to set them free-moving. I think this causes here a side effect to temporary text selection disablement which is another necessity to prevent messing up the view during drag/resize operations.

Since the .wcDisableSelection is applied only to main container, floating panels are not taking it.
Preventing the text selection on the whole "body" would be a better action.

Please see the [suggested fix] (https://github.com/WebCabin/wcDocker/compare/master...bulentv:selectionFix)

**Comment by Lochemage** [comment]
@bulentv 

You bring up a good point. It used to be that the floating panels appear inside the docker container element, but I have since moved it out so the panels can move more freely. I guess I forgot about the select class.

**Comment by Lochemage** [comment]
@bulentv 

I have move the class to the body element, let me know how that works for you.

**Comment by Lochemage** [comment]
@bulentv 

Closing this issue, please re-open if you find any problems with it.
