### ISSUE TITLE
SSL Demo site is not loading

### ISSUE THREAD

**Issue by bulentv** [WebCabin/wcDocker#55]
@Lochemage,

I think something is  wrong with either the SSL certificate or the server itself at https://docker.webcabin.org. It is not loading. Non-SSL site is fine.

![image](https://cloud.githubusercontent.com/assets/813743/8950157/386aa7fa-35c6-11e5-83bc-a3d83a921786.png)

**Comment by Lochemage** [comment]
@bulentv 

You are correct, I've removed SSL as it was unnecessary.  There is nothing to be kept secure.

**Comment by Lochemage** [comment]
@bulentv 

Closing this issue. Please re-open if SSL is really that important to you, and if so, please tell me why.

**Comment by bulentv** [comment]
@Lochemage 

SSL is not actually important but my point is that "the demo link on the github description of the project" points to SSL site while the SSL site is not functioning properly. Sorry for forgetting to mention this :)

![image](https://cloud.githubusercontent.com/assets/813743/9343651/edaa0b60-460b-11e5-89d8-758a6d21e287.png)

**Comment by Lochemage** [comment]
@bulentv 

Ah, thanks for catching that one, I thought I had fixed all the references.
