### ISSUE TITLE
moveable(false) is not fully preventing the panel move.

### ISSUE THREAD

**Issue by bulentv** [WebCabin/wcDocker#58]
Assume that we have a "fixed" panel made by calling movable(false) & closable(false) just like the header on the demo page.

If we drag one of the other panels next to the "fixed" panel, it is actually possible to dock it between the windows edge and the fixed panel. This causes the fixed panel to move to the position after the newly docked panel.

As it is not easy to reproduce this problem, I uploaded a video of it.
http://youtu.be/r593qJTiMks

Bulent

**Comment by Lochemage** [comment]
@bulentv 

Nice catch, it's a bit too late for me to look into this one right now. About to sleep, but I will look into this one asap.

**Comment by Lochemage** [comment]
@bulentv 

I have checked in a fix for this issue, please let me know if you find any more issues.

**Comment by bulentv** [comment]
@Lochemage 

Thanks, it looks better. If I leave only one docked panel along with the fixed panel I can no longer reproduce the issue.

But I still able to reproduce a similar issue in a slightly different way. If we left one docked and another floating panel we can dock the floating panel to a place between the container edge and the fixed panel, where I believe should be prohibited. Can be seen on the this new screen record : 
http://youtu.be/W_uvI7Pc9zk

**Comment by Lochemage** [comment]
@bulentv 

Your video is private so I can't see it, but I found the issue you are talking about and am on it, thanks!

**Comment by bulentv** [comment]
Oops sorry, I made it unlisted now.

**Comment by Lochemage** [comment]
@bulentv 

I've made an update that should fix this issue as well, please let me know if you find any further issues!

**Comment by bulentv** [comment]
@Lochemage 

Thank you, it looks good.

**Comment by Lochemage** [comment]
@bulentv 

Great, going to close this issue. Feel free to reopen if it comes back again!
