### ISSUE TITLE
CRLF line endings

### ISSUE THREAD

**Issue by bulentv** [WebCabin/wcDocker#62]
@Lochemage 

Is that the repo storing the code files with windows-style CRLF line endings? I am using linux and somethimes git is thinking that all the lines are modified while I change just a few lines. When I check the differencies, I always found that the original file is CRLF and modified one is a LF style file.

I think a .gitattributes file may need to be added to the repo (and maybe a line ending fix commit). According to information I found on the web, that file is taking care of the platform differences in terms of line endings.

If you see this is an issue to be fixed, I can work on the possible solutions.

Related pages for information :
https://help.github.com/articles/dealing-with-line-endings/
http://stackoverflow.com/questions/8461528/replace-github-repo-while-preserving-issues-wiki-etc

**Comment by Lochemage** [comment]
@bulentv 

I have added a gitattributes file, I am not entirely sure how this works, it didn't seem to make any of my current files change to LF style, but that may just be because I am running on Windows.

I am going to rely on you to let me know if this corrects the line endings on your side.

**Comment by bulentv** [comment]
@Lochemage 

.gitattributes looks correct to me. But the files are still being checked out as CRLF and it turns out that there is one more change to make the repo cross-compatible in line-endings aspect.

I did it on my fork and tested on both windows and linux. Windows version of git checks out the files with CRLF and linux git does only LF, and also does the reverse on commit/push which is what is what exactly expected.

But as you can see, unfortunately this commit touches every single file that is listed as text in .gitattributes to remove "CR" to make it compatible which is kind of a huge change tough there is absolutely no change on the code. 

I'm making this as a pull request. So as the owner of the repo, it is up to you to accept it and pull the commit or not.

There is an alternative solution that [does the same but in the whole history] (http://stackoverflow.com/questions/2466959/git-removing-carriage-returns-from-source-controlled-files) of repo and without changing or adding any commits.

**Comment by Lochemage** [comment]
@bulentv 

I've merged your update! It looks like fixing the entire history of the project might not be a good idea as it will force all users to re-pull a brand new repo. I think it should be ok, though, you don't plan to roll-back to a previous version, do you?

**Comment by bulentv** [comment]
Wow, thank you for accepting it! And no I don't plan a roll-back.
So, now I can do more contribution to leave this very commit in the past :)

**Comment by Lochemage** [comment]
@bulentv 

Great! I look forward to more contributions!
