### ISSUE TITLE
how to use the intern/low-level classes ? 

### ISSUE THREAD

**Issue by gbaumgart** [WebCabin/wcDocker#64]
Hi,
most of the classes are for wcDocker's internal use. I was wondering I could use them without a wcDocker instance. 

Actually I just need to know how to build a custom layout or a grid if you like. Lets say a main/center region with a bottom area, preferably with a custom splitter(see toggle-button in the status-bar) to expand /resize the status area: 
![image](https://cloud.githubusercontent.com/assets/1205100/9577823/2d0cf3ca-4fe5-11e5-96eb-c331917917cf.png)

what you think, is that possible? the sample files show something about custom layouts but they assume also a wcDocker instance which I want to avoid at any cost(each instance draws a hell of performance). 

any hint or snippet is welcome, thank you again!
guenter

**Comment by Lochemage** [comment]
@gbaumgart 

You should be able to use it directly if you want. There are some references within `wcPanel` that expects its `_parent` object to have the functions `docker()` and more recently `instanceOf()`, but those are only if you plan to use the layout as a docking target via function `wcLayout.__checkAnchorDrop()`.

Also of note, layouts have an `__update()` function. Currently this does nothing, but there's always a chance that it may become necessary for proper a update.

**Comment by gbaumgart** [comment]
'got' it!

**Comment by Lochemage** [comment]
@gbaumgart 

Update, wcLayout is now a base class object for both wcLayoutSimple and wcLayoutTable and it is now theoretically possible to subclass your own layout type; although it has not been tested.
