### ISSUE TITLE
wcPanel.close() is closing the wrong tabbed panel

### ISSUE THREAD

**Issue by bulentv** [WebCabin/wcDocker#67]
I'm trying to dynamically create / close tabbed windows. So I'm using wcDocker.addPanel and wcPanel.close() members to do this. But if the order of .close() calls ar not same with the .addPanel() calls, wcDocker is closing a different tabbed panel instead of the one is called.

Please take the slightly modified demo.js from [here](https://github.com/bulentv/wcDocker/blob/wcPanel_close_issue/demo.js) and try to run /indexDev.html with devtools open. There are two 'debugger;' calls to stop the execution on the lines that creation of the panels and close calls.

**Comment by Lochemage** [comment]
@bulentv 

I am seeing this problem and know why it is happening, I should have a fix soon.

**Comment by Lochemage** [comment]
@bulentv 

This should be working properly now, please let me know if you are still finding a problem with this.
