### ISSUE TITLE
Error while restoring layout

### ISSUE THREAD

**Issue by arpanmukherjee1** [WebCabin/wcDocker#70]
Steps to reproduce:
1. In the demo close all panels except a floating panel (control panel).
2. Save the layout and try to restore it.
3. error `Cannot read property '__restore' of undefined`

**Comment by Lochemage** [comment]
@arpanmukherjee1 

Thank you for pointing this out, I see the problem and should have a fix for it soon!

**Comment by Lochemage** [comment]
@arpanmukherjee1 

I've checked in a fix for this, please let me know if you are still seeing this problem.
