### ISSUE TITLE
Collapsable panel does not overlap floating panel

### ISSUE THREAD

**Issue by arpanmukherjee1** [WebCabin/wcDocker#74]
Screenshot attached.

![overlap](https://cloud.githubusercontent.com/assets/10557028/10017933/1d0677f4-6150-11e5-9cce-2814ca27efbc.jpg)

I think z-indexs need to be provided at runtime. Also ref issue #39 that needed cycling of z-indexes.

I patched the bug by introducing a function 

```javascript

            __fixZIndex: function () {
                var from = this._floatingList.indexOf(this._focusFrame);
                var to = this._floatingList.length - 1;

                this._floatingList.splice(to, 0, this._floatingList.splice(from, 1)[0]);

                var length = this._floatingList.length;
                var start = 40;
                var step = 2;
                var index = 0;
                var panel;

                for (var i = start; i <= (start + (length - 1) * step) ; i += step) {

                    index = ((i - start) / step);
                    panel = this._floatingList[index];
                    if (panel) {
                        panel.$frame.css('z-index', i);
                        panel.__trigger(wcDocker.EVENT.Z_INDEX_CHANGED);
                    }
                }
            },
```
that is called when an panel is added or focused. `Z_INDEX_CHANGED` event is handled by IFRAME to update it's `z-index = z-index of frame + 1`.

But it looks like this no more works. Still digging more into this.

Any suggestions on fixing this?

**Comment by Lochemage** [comment]
@arpanmukherjee1 

Thank you for this, I am looking at it now

**Comment by Lochemage** [comment]
@arpanmukherjee1 

I have implemented your change with some slight modification. Please re-open if you find a problem.
