### ISSUE TITLE
docker::addPanel(....,options) not used

### ISSUE THREAD

**Issue by gbaumgart** [WebCabin/wcDocker#77]
on line 315 or so, its not using the argument options:

var panelOptions = (panelType.options && panelType.options.options) || {};

it should be 

var panelOptions = (panelType.options && panelType.options.options) || options || {};

**Comment by Lochemage** [comment]
@gbaumgart 

Actually the code you see is not a bug, the options passed into the `addPanel` method is different than the one used to construct the panel object itself. This is actually a bug in the documentation, because the two options should be different.

**Comment by gbaumgart** [comment]
ok, just to let know. my 'fix' enables to register a panel sometime but alter it later with addPanel.  something i do quite often.

**Comment by Lochemage** [comment]
@gbaumgart 

I'm not sure this makes sense to allow panel construct options during the `addPanel`. The only way to include options during the addPanel is if it was hard coded, but this is not the case if the user dynamically adds the panel themselves (via right click, add panel menu). The idea is that all of the constructor options are pre-defined when the panel type is registered so that any time the panel itself is created by the user, those options would be used.

**Comment by gbaumgart** [comment]
okok. I've got my own context menu and my own persistence solution....
ok never mind, i will add the fix in my panel class. most of the cases, I do only register a few panel types: 'default tab', 'default fixed' and so on. later on i usually do add a panel of that type, but I do change title, icon and a few other things, that's why the option argument should be evaluated over the panel-type options... 

g

**Comment by Lochemage** [comment]
@gbaumgart 

Just FYI, you can change the registered panel options dynamically any time through code with [`wcDocker.panelTypeInfo()`](http://docker.api.webcabin.org/module-wcDocker.html#toc21)

```
// opts here will be the complete options of the registered panel type
var opts = myDocker.panelTypeInfo('my panel');

// Retrieve the options property inside for the options object that is passed into the 'onCreate' constructor.
var panelOpts = opts.options;

// Change some properties...
opts.faicon = "bell-o";
panelOpts.customProp = "foo";

// Add the panel, who now uses new modified options.
myDocker.addPanel('my panel', wcDocker.DOCK.LEFT);
```

**Comment by gbaumgart** [comment]
yeah, got it but its really not the same effect, just more code compared to "|| options". never mind and thanks for the heads up

**Comment by Lochemage** [comment]
@gbaumgart 

I understand it may be inconvenient, it's just that the options passed into `addPanel` is used for something else and has its own definition of properties, which means it not necessarily compatible with the options passed into the panel's constructor.  Also, simply using an `||` operator means that your options will only be used if the panel was not registered with any for itself. The proper way to do it would be to combine the two potential options and have the `addPanel` options overwrite the other.

**Comment by gbaumgart** [comment]
ok, will try that! thanks Jeff.

any news about wcCore ? otherwise i really just do all just in 
wcDocker/_Evented : on/emit/own(track global handlers)
wcDocker/_Func : debounce/eventify etc...
wcDocker/_ContainsWidgets : own(track widgets and destroy/null them automatically)

 g

**Comment by Lochemage** [comment]
@gbaumgart 

Could you remind me what you mean by wcCore?  Is this different than wcDocker's base class that exists now wcBase?

**Comment by gbaumgart** [comment]
ahm, can't remember right now but yeah, that's pretty much the plan for me. that would also enable to 'shim' some parts away to other libraries. Somehow the idea was also to get closer to wcDocker internals and to some degree enable me to do optimizations or changes. What troubles me most is that the eventing/callback part is messing lots of pure functional code and I hope to use dcl's AOP feature to 'eventify' the actual code on the fly, at least enough to change here and there things. I have that pattern in quite many places to fix, eg: proxying an API from one to many sub widgets like resize..

however, its probably not quite on your list, so don't bother too much about :-)
