### ISSUE TITLE
a few questions regarding unit-tests

### ISSUE THREAD

**Issue by gbaumgart** [WebCabin/wcDocker#78]
Hi,
I am on it and 2 burning questions came up:

1. how do I fully & cleanly destroy a docker instance ? __destroy is missing and clear doesn't seem to remove all event handles. 
2. how can I programmatically move panels into layouts? ie: we 2 tabs : "A" and "B" and I want to call something like A.addPanel(direction|position as in panel options during panel creation). Possibly I missed something in the API.

thanks!

**Comment by Lochemage** [comment]
@gbaumgart 

Good question, destroying the docker instance hasn't really come up before so it's likely that it just does not exist.

You should be able to move a panel by using `wcDocker.movePanel()`. I'm not entirely sure what you mean by the tabs, but that function should allow you to do anything you need.

**Comment by gbaumgart** [comment]
ok, thanks! 
that means: 

1. add as first event related functions in wcDocker/base: to collect event handles. that was missing anyways (because $('body').off() won't do it). So docker::destroy will remove that handles.
2. fine, that should do. 

ok, will push a PR this week about. 
g

**Comment by gbaumgart** [comment]
about events: i would add this here to base : https://github.com/gbaumgart/xbox-app-orginal-dump/blob/master/client/src/lib/xide/mixins/EventedMixin.js (slightly modified/optimized).

**Comment by gbaumgart** [comment]
or what about a wcCore package ?

**Comment by gbaumgart** [comment]
ok, never mind. i wrote some little code to collect all that $('body').on handles and implemented docker::__destroy :


1. call off for all body handles
2. clear the this._updateId timeout loop
3. clear all handles in _events
4. delete and null out all properties in docker 

is there anything else I should do to clear a docker instance ? 

I will put this now together with the lodash dep in a PR for Friday.

**Comment by Lochemage** [comment]
@gbaumgart 

Are you sure we need to manage jQuery events? I'm pretty sure jQuery cleans them up itself, if you remove the DOM element tied to an event, it should automatically unbind itself.

**Comment by gbaumgart** [comment]
Only if you're listening to body events, those event handlers remain active. (I do create lots of wcDocker instances and I need them to properly to shutdown)

**Comment by gbaumgart** [comment]
thats how currently do it in a docker subclass: 

```javascript
__eventHandles:[],
        destroy:function(){
            registry.remove(this.id);
            this.__destroy();
        },

        __on:function(element,type,selector,handler){

            if(typeof selector =='function' && !handler){
                //no selector given,
                handler = selector;
                selector = null;
            }

            element.on(type,selector,handler);

            this.__eventHandles.push({
                element:element,
                type:type,
                selector:selector,
                handler:handler
            });

        },
        __destroy:function(){
            var self = this;

            _.each(this.__eventHandles,function(handle){
                handle && handle.element && handle.element.off(handle.type,handle.selector,handle.handler);
                this.__eventHandles.remove(handle);
            },self);


            _.each(this._events,function(handles,type){
                _.each(handles,function(handler){
                    self.off(type,handler);
                });
            });

            this.clear();

            delete this._events;
            delete this.__eventHandles;

            this._updateId && clearTimeout(this._updateId);
        },
        __init:function(){
             var body=$(body), self = this;
             self.__on(body,'mousemove',__onMouseMove);
        }

```

**Comment by Lochemage** [comment]
@gbaumgart 

ah, I understand. You're right.

**Comment by gbaumgart** [comment]
I remember now, wcCore was needed to get rid of this sort of code. As mentioned, I gonna get my hands soon on wcDocker. And I think events, shims and widget handling should go in there. Most attractive ideals seem to be in https://github.com/ibm-js/delite and https://github.com/ibm-js/decor. it has already dcl...

So, what you think, does a wcCore makes sense to you too? I'd just type something together and lets try from there.

**Comment by gbaumgart** [comment]
ups, i meant wcPlay, sorry...being sick here

**Comment by gbaumgart** [comment]
that's what i have to do at work,
http://pearls-media.com/screenshots/Screenshots.html

:-)

**Comment by gbaumgart** [comment]
ok, new PR opened! its really just adding test-units and lodash. I will do investigate as next the entire code in order to find improvements; then implement changes/proposals regarding lodash/performance/API/dcl pimps as test-units first (for your review).
