### ISSUE TITLE
Is it possible to disable the context menu that shows up on right click?

### ISSUE THREAD

**Issue by azeyad** [WebCabin/wcDocker#84]

**Comment by gbaumgart** [comment]
yes, please see demo sources, 

just add allowContextMenu:false in your options.

**Comment by Lochemage** [comment]
@azeyad 

Yes, as @gbaumgart says, it can be disabled.  Please close this ticket if this suits your needs.

Thanks

**Comment by azeyad** [comment]
Thanks a lot guys
