### ISSUE TITLE
Is there any way to intercept a panel's event, and cancel it if needed?

### ISSUE THREAD

**Issue by azeyad** [WebCabin/wcDocker#86]
For example the EVENT.CLOSED, I want to be able to cancel it from the event handler function, like asking the user if he really wants to close the panel and in case he answered no I want to mark the event as handled without actually closing the panel

**Comment by gbaumgart** [comment]
@Lochemage : i tried overriding wcPanel::close but it wasn't called when hitting the close button. otherwise it would have been an easy piece

**Comment by Lochemage** [comment]
@azeyad 

Currently, there is no feature like this; by the time you receive the close event, it is already too late. I'll need to investigate the best way to implement this, but it most likely will require you to change a value passed in to the event handler:

```
myPanel.on(wcDocker.EVENT.CLOSED, function(e) {
  // Show your confirmation box and then set the cancel 
  // property true if you want to cancel the close event.
  if (confirm('Are you sure you want to close this panel?')) {
    e.cancel = true;
  }
});
```

This will probably get a little more complicated if your confirmation box does not block the thread. Here we assume a function `showConfirmation` exists that displays a non-blocking confirmation screen:

```
var hasConfirmed = false;
myPanel.on(wcDocker.EVENT.CLOSED, function(e) {
  // In this case, immediately cancel the event if the user has not confirmed yet.
  if (!hasConfirmed) {
    e.cancel = true;

    // Show the confirmation box, which registers a handler for when a response is made.
    showConfirmation(function(response) {
      // If the user has confirmed the close...
      if (response) {
        // Make sure we flag it confirmed, so the next time the closed event is fired,
        // we don't show the confirmation box again.
        hasConfirmed = true;
        myPanel.close();
      }
    });
  }
});
```

Let me know if this works for you, and I will begin implementing it.

**Comment by azeyad** [comment]
@Lochemage: Thanks a lot for your response and yes this is what I am looking for, I think this is somehow similar to the windows forms events I used to deal with in the past.

**Comment by gbaumgart** [comment]
yeah, i would also love to see the events functions improved:
I am using this here (returns handlers result)
```js

eventedClass = {
    _emit:function (type) {
        if (!this.__events)
            return;

        if (arguments[2] === true)
            throw new Error("Please use emit.sticky() instead of passing sticky=true for event: " + type);

        var handler = this.__events[type],
            eventArgs = arguments.length > 1 ? arguments[2] : null;

        if (!handler)
            return;

        var returnValue;

        if (typeof handler == 'function') {
            switch (arguments.length) {
                // fast cases
                case 1:
                    return handler.call(this);
                case 2:
                    return handler.call(this, arguments[1]);
                case 3:
                    return handler.call(this, arguments[1], arguments[2]);
                // slower
                default:
                    var args = Array.prototype.slice.call(arguments, 1);
                    returnValue = handler.apply(this, args);
            }
        }

        else if (isArray(handler)) {
            var args = Array.prototype.slice.call(arguments, 1);
            var listeners = handler.slice(), temp;
            for (var i = 0, l = listeners.length; i < l; i++) {
                temp = listeners[i].handler.apply(this, args);
                if (temp !== undefined)
                    returnValue = temp;
            }
        }

        return returnValue;
    },
    _on: function(type, listener,owner) {
        
        if (!this.__events) this.__events = {};

        if (!this.__events[type]) {
            this.__events[type] = [];
        }

        var eventList = this.__events[type];
        if (!eventList) {
            // Optimize the case of one listener. Don't need the extra array object.
            this.__events[type] = listener;
        }
        else if (_.isArray(eventList)) {

            if (eventList.indexOf(listener) != -1)
                return console.warn("adding same listener twice", type);

            // If we've already got an array, just append.
            var _handle = {
                handler: listener,
                owner: owner || this,
                type: type,
                remove: function () {
                    eventList.remove(this);
                }
            };
            eventList.push(_handle);
            return _handle;
        }
        return this;
    },
    /**
     * Returns an array of listeners for the specified event. This array can be
     * manipulated, e.g. to remove listeners.
     *
     * @name emitter.listeners(event)
     * @param {String} events - The event name/id to return listeners for
     * @api public
     *
     * ```javascript
     * session.on('change', function (stream) {
         *     console.log('session changed');
         * });
     * console.log(util.inspect(session.listeners('change'))); // [ [Function] ]
     * ```
     */
    listeners:function(type) {
        if (!this.__events) this.__events = {};
        if (!this.__events[type]) this.__events[type] = [];
        if (!isArray(this.__events[type])) {
            this.__events[type] = [this.__events[type]];
        }
        return this.__events[type];
    },
    /**
     * Clean up handles
     * @private
     */
    _destroyHandles: function () {
        if (this.__events) {
            for(var type in this.__events){
                _.each(this.__events[type], function(item){
                    if(item && item.remove){
                        item.remove();
                    }
                });
            }
            delete this.__events;
        }

    }
}

```

**Comment by Lochemage** [comment]
@gbaumgart 

I would like to do a simple return value as well, the only problem with it is what to do if you have multiple event handlers all returning their own result.  In your solution above, it seems you simply use the latest event's result that is not empty and ignore all others.  I don't quite like the idea of losing potentially important event results like that, so I think what I will do is store all results in an array that can be handled however the trigger-er intends (whether it be just ignoring all but one or somehow combining the results).

In light of this, the new close event would look more like this instead:

```
myPanel.on(wcDocker.EVENT.CLOSED, function() {
  // Return false to cancel the event.  If undefined or anything else is returned, I will assume the panel should close as normal.
  return false;
});
```

And similar for the asynchronous version:

```
var hasConfirmed = false;
myPanel.on(wcDocker.EVENT.CLOSED, function() {
  // In this case, immediately cancel the event if the user has not confirmed yet.
  if (!hasConfirmed) {
    // Show the confirmation box, which registers a handler for when a response is made.
    showConfirmation(function(response) {
      // If the user has confirmed the close...
      if (response) {
        // Make sure we flag it confirmed, so the next time the closed event is fired,
        // we don't show the confirmation box again.
        hasConfirmed = true;
        myPanel.close();
      }
    });

    return false;
  }
});
```

**Comment by Lochemage** [comment]
@azeyad, @gbaumgart 

Alright, I have implemented it, but it ended up being a little different than the above. It occurred to me that, in some cases, as soon as `wcDocker.EVENT.CLOSED` has been triggered, things may be unloaded. For example, the `wcIFrame` object ties directly into it's owner panels' closed event, as soon as it is triggered, it will shut down and remove the frame. The solution was to create a new event type `wcDocker.EVENT.CLOSING` that is called first before the closed event.  If any handler within this new event returns any falsey value, the closed event will be cancelled and therefore will never be triggered.

Here is some example code:

```
var hasConfirmed = false;
myPanel.on(wcDocker.EVENT.CLOSING, function() {
  // If we have not received confirmation to
  // close this panel, ask for it now!
  if (!hasConfirmed) {
    // For testing purposes, I add a quick timeout to make
    // it simulate an asynchronous action.
    setTimeout(function() {
      // Show the confirmation popup.
      if (confirm('Are you sure you wish to close this panel?')) {
        // If the user confirms, we first flag that the 
        // user has made the confirmation, so when it
        // returns to this event handler, it will actually
        // allow the panel to close.
        hasConfirmed = true;
        myPanel.close();
      }
    }, 1);

    // Return false immediately to cancel the close event.
    return false;
  }

  // If we get here, the user has confirmed the event, we should
  // allow the panel to close now.
  return true;
});
```

Also, documentation on this new event can be found here: http://docker.api.webcabin.org/module-wcDocker.html#toc4

Please let me know if there are any issues, otherwise I ask that you close this issue :)

**Comment by gbaumgart** [comment]
:+1: thanks!

**Comment by Lochemage** [comment]
Also note, the return value for the events can now be used for other things, as well as your own private events you may be using. All result values are returned from `wcDocker.trigger` and `wcPanel.trigger` as an array of values.

**Comment by gbaumgart** [comment]
but yeah, it would be great if you/we can add an "off" for these events, also clean them really on destroy. (same goes for the global events in wcDocker it self as already mentioned); but never mind, i got this all done in my version. In Dojo you get actually a handle(as shown) back when subscribing to events, this makes reusing of widgets possible for instance but also ensures all gets wiped properly on destroy.

**Comment by azeyad** [comment]
@Lochemage: I just wanted to thank you for the quick turnaround, the fix would work for me but I still did not try yet, I couldn't see the new event in the documentation though, but I am closing the issue anyway.

**Comment by Lochemage** [comment]
@azeyad:

Most likely, you're looking at an old cashed version of the API doc page. Try clearing your browser cache and view again.
