### ISSUE TITLE
Create ghost from non-wcDocker elements?

### ISSUE THREAD

**Issue by gbaumgart** [WebCabin/wcDocker#88]
Hi Jeff, I hope you had a nice new year! 

Might it be possible to turn non-wcDocker elements into wcGhosts and when dropped to add a panel to the wcDocker instance? Its a little hard to explain, so here a picture:

The accordion tabs on the right ( "Script") are non-wcDocker & ordinary HTML elements. I am looking for an idea to turn them into a wcGhost as soon I start dragging them. I don't expect a full answer from you but what you think about this steps: 

1. when start dragging, I create a wcPanel just at the position/size of my HTML
2. somehow I would need to set the panel already into a 'dragging' state inside the docker instance. 
3. from here, wcDocker would create wcGhost for me and proceed as normal. In case, its aborted, I have to destroy that panel my self again. 
4. in case that panel got dropped, I move my content into that panel.

Could that work? In my case its a little more complicated: I have a main wcDocker instance which contain other wcDocker instances ('min.xblox') but containing other tab/accordion widgets. The goal is to enable the user to detach non-wcDocker containers and then add it to wcDocker instance as ordinary panel. I can do this also as context - menu action "detach" but I'd prefer Drag'n drop.

Well, don't bother too much, just asking.

**Comment by Lochemage** [comment]
@gbaumgart 

Excellent idea!  In fact, good news, this feature already exists! Take a look at the tutorial page: http://docker.api.webcabin.org/tutorial-2.0-tips-and-tricks.html#toc8

Simply add the CSS class `"wcCreatePanel"` to any HTML element along with the data attribute `data-panel` that names the panel to create, and any time the user clicks and drags that element, it will act as though you are dragging a newly created panel.

You can also see a live demonstration on the demo page http://docker.webcabin.org/. On the left side there is a collapsed panel named `'Creation Panel'`

Please let me know if this solves your issue!

**Comment by gbaumgart** [comment]
that's just fecking awesome, Thanks Jeff! I didn't test it yet but I guess that will do! I will let you know how it goes. Shall we close this now?

**Comment by gbaumgart** [comment]
Yes, that works! The only problem is that its creating 2 panels:
![image](https://cloud.githubusercontent.com/assets/1205100/12178761/80ceab5e-b573-11e5-9dc6-769fb3fae105.png)

This is is because there are indeed 2 dockers in the scene. I will check the sources to figure out:

- how to add a callback to avoid multiple panel creation 
- using the source node: $toggleNode.data('panel', 'DefaultTab') as event receiver in order to manipulate the panel creation a bit better. For instance, selecting the target docker instance, but also to transfer my content into the newly created panel....

Ok, for me this is solved. If there is any core updates I can offer in regard of multiple docker instances, I will let you know.

**Comment by Lochemage** [comment]
@gbaumgart 

Ahh, that makes sense, I never really use more than one docker.  When you create these panels, could they be dropped into both docker areas? I may have an idea to solve this, but I just started my day at work so I won't get to it until late tonight at the soonest.

**Comment by gbaumgart** [comment]
Yeah, actually it depends on the case, some times I want to move one panel (created with wcCreatePanel) to another docker or limit it to the originating docker. I already have an idea to avoid those duplicates: 
in the wcDocker/docker module, there should be a singleton object for events which make only sense once (exactly like wcCreatePanel). This singleton object should collect all instances. 

However, I found __onMouseDownCreatePanel and its not really fitted yet. It reacts on mouse-down whilst it should create the new panel only on drag. I will re-implement this feature this week or next and I hope I will have a PR for you, this will also include some patches to get rid of all that $('body').on listeners which are bad when using multiple & destroyable dockers. Ok, I will let you know as soon its done! 

Thanks again

**Comment by gbaumgart** [comment]
@offtopic btw: if you want to see wcDocker in one of my [apps](https://github.com/gbaumgart/xamiro/tree/2.0). Its currently alpha but will serve as base for full featured IDE for home-automation...

**Comment by Lochemage** [comment]
@gbaumgart 

In that case, perhaps it is best since you are directly using this, I will hold on this and leave it up to you!  I look forward to what you come up with!

**Comment by Lochemage** [comment]
@gbaumgart 

Also, I meant to ask this before, but I keep forgetting... I like the screenshot or your interface, have you had any thought on sharing the theme?

**Comment by gbaumgart** [comment]
yeah, thought soo too. its getting too custom anyways,

theme: the base is here: https://github.com/gbaumgart/bootrap-light-blue-admin-theme. and the overlay for wcDocker comes later, its not quite finish yet (tab rotation). i will let you know 
g

**Comment by gbaumgart** [comment]
@Lochemage. About the theme again: I got the tab-bar rotation problem fixed but I don't know how to deploy a regular wcDocker theme from it since its all SASS & Bootstrap based. If you like we could discuss this in another thread. Up to you. There are also slight changes in the code needed. In fact there is little left from styles.css and themes/theme.css. Extracting the classes manually would do too but I think its too annoying to build the theme on your side or your users, it needs also 'compass' installed(ruby & rails). However, me and the original author are constantly working on this theme. With the raise of Bootstrap - v4 in SASS it can only get better.
