### ISSUE TITLE
Adding the last panel in a floating panel cause crash (infinity loop)

### ISSUE THREAD

**Issue by AFamularo-lomoSoft** [WebCabin/wcDocker#93]
Hello Jeff, 

I'm college of lomotelch, we work together on a project.

Scenario: 
- We have a main panel with a table. This table contains customer (e.g.). The user can double click one customer row to open a new panel to edit/view the customer data.

Steps:
- Load the page
- Double click on one row with CustomerID "VICTE"
- A new detail view will open as a stacked panel (parent: Overview)
- Move the "overview" in the middle of the screen to create a floating panel
- Now move the user detail in the floating panel
- Now the docker crashes

Investigating:
I indicate the source of the infinity loop in the event "onMouseUp".

// Dragging the entire frame.
if (!self._draggingFrameTab) {
 var rect = self._ghost.rect();
 if (!rect.tabOrientation) {
   rect.tabOrientation = self._draggingFrame.tabOrientation();
  }
  while (self._draggingFrame.panel()) {
    self.movePanel(self._draggingFrame.panel(), wcDocker.DOCK.STACKED, panel, rect);}

This while-loop does not end.

[Error with floating panel.docx](https://github.com/WebCabin/wcDocker/files/150790/Error.with.floating.panel.docx)
[wcDocker.zip](https://github.com/WebCabin/wcDocker/files/150813/wcDocker.zip)
//Please run bower install to the components. 

Many thanks.

Best,
Alexander

**Comment by Lochemage** [comment]
@AFamularo-lomoSoft

Thanks, I believe I understand why this is happening. I should be able to fix it later tonight, after I get home from work!

**Comment by Lochemage** [comment]
@AFamularo-lomoSoft 

This issue should be fixed now, please let me know if you find anything else.
