### ISSUE TITLE
split programmatically?

### ISSUE THREAD

**Issue by gbaumgart** [WebCabin/wcDocker#97]
Hi,
I am having a little difficult time to implement some generic user-actions like "Split-Horizontal/Vertical" on an existing frame with multiple tabs. Problem is that unfortunately most of the docking code is within mouse handlers and its little hard to understand since it also depends on a dragging object. I think its a general problem with wcDocker that this quit important functions are not wrapped or isolated functions (being aware of performance impacts). By having them, we might have also an easier base beside the restore/save layout API. No offense, just experience ;-)

Would you mind to write some pseudocode down? Let's say for simple case: wcFrame with 2 loose panels (top tabs):

something like:
- create splitter(hori or vertical)
- docker.movePanel(panel-1/panel-2) into splitters

I am trying to implement a complete API to have it similar as in Jet-Brain's IDEs (lots of tab actions).

![image](https://cloud.githubusercontent.com/assets/1205100/13571079/d3d708fe-e472-11e5-97ca-4ec4e1ffe0c5.png)

Jetbrains:
![image](https://cloud.githubusercontent.com/assets/1205100/13571125/215cf19c-e473-11e5-9bbc-fed5e1a50afd.png)

**Comment by gbaumgart** [comment]
after that, I am actually ready to release some wcDocker [extras](https://gitlab.com/xamiro/xdocker), together with the used themes. It would be an extra package you can add in top of wcDocker. It has a quite few extra dependencies then of course.

**Comment by Lochemage** [comment]
@gbaumgart 

Did you mean to close this issue?  It seems like it hasn't been addressed.

I suppose the project is due for some code cleanup, I'll see what I can do to extrapolate some of the more useful functionality.

For reference, if I am understanding you correctly, you want to be able to create your own menu item that can split a two or more tabbed frame into two separate panels. The same as if the user dragged one of those tabs out and docked it right along side?

**Comment by Lochemage** [comment]
@gbaumgart 

Also, unless I am understanding you wrong, this might be what you want: http://docker.api.webcabin.org/module-wcDocker.html#toc18

`wcDocker.movePanel` should allow you to move one of the two tabbed panels and dock it next to the original. It just requires the two wcPanel objects, then you can set the location to `wcDocker.DOCK.LEFT` or whatever to automatically generate a split between them.

**Comment by gbaumgart** [comment]
@Lochemage , yeah, figured that out now too ;-)

**Comment by gbaumgart** [comment]
btw, could make progress with the resize problem (dont move dom elements)?
